// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'currency.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

// ignore: non_constant_identifier_names
_$_Currencies _$$_CurrenciesFromJson(Map<String, dynamic> json) =>
    _$_Currencies(
      bbd: Aed.fromJson(json['bbd'] as Map<String, dynamic>),
      usd: Aed.fromJson(json['usd'] as Map<String, dynamic>),
      xaf: Aed.fromJson(json['xaf'] as Map<String, dynamic>),
      brl: Aed.fromJson(json['brl'] as Map<String, dynamic>),
      eur: Aed.fromJson(json['eur'] as Map<String, dynamic>),
      aud: Aed.fromJson(json['aud'] as Map<String, dynamic>),
      kid: Aed.fromJson(json['kid'] as Map<String, dynamic>),
      ron: Aed.fromJson(json['ron'] as Map<String, dynamic>),
      lak: Aed.fromJson(json['lak'] as Map<String, dynamic>),
      xof: Aed.fromJson(json['xof'] as Map<String, dynamic>),
      iqd: Aed.fromJson(json['iqd'] as Map<String, dynamic>),
      kes: Aed.fromJson(json['kes'] as Map<String, dynamic>),
      kyd: Aed.fromJson(json['kyd'] as Map<String, dynamic>),
      gnf: Aed.fromJson(json['gnf'] as Map<String, dynamic>),
      tnd: Aed.fromJson(json['tnd'] as Map<String, dynamic>),
      bob: Aed.fromJson(json['bob'] as Map<String, dynamic>),
      cny: Aed.fromJson(json['cny'] as Map<String, dynamic>),
      krw: Aed.fromJson(json['krw'] as Map<String, dynamic>),
      kwd: Aed.fromJson(json['kwd'] as Map<String, dynamic>),
      dzd: Aed.fromJson(json['dzd'] as Map<String, dynamic>),
      awg: Aed.fromJson(json['awg'] as Map<String, dynamic>),
      rub: Aed.fromJson(json['rub'] as Map<String, dynamic>),
      dkk: Aed.fromJson(json['dkk'] as Map<String, dynamic>),
      gbp: Aed.fromJson(json['gbp'] as Map<String, dynamic>),
      twd: Aed.fromJson(json['twd'] as Map<String, dynamic>),
      cad: Aed.fromJson(json['cad'] as Map<String, dynamic>),
      fjd: Aed.fromJson(json['fjd'] as Map<String, dynamic>),
      xpf: Aed.fromJson(json['xpf'] as Map<String, dynamic>),
      pen: Aed.fromJson(json['pen'] as Map<String, dynamic>),
      clp: Aed.fromJson(json['clp'] as Map<String, dynamic>),
      egp: Aed.fromJson(json['egp'] as Map<String, dynamic>),
      mkd: Aed.fromJson(json['mkd'] as Map<String, dynamic>),
      bdt: Aed.fromJson(json['bdt'] as Map<String, dynamic>),
      sgd: Bam.fromJson(json['sgd'] as Map<String, dynamic>),
      etb: Aed.fromJson(json['etb'] as Map<String, dynamic>),
      bsd: Aed.fromJson(json['bsd'] as Map<String, dynamic>),
      tmt: Aed.fromJson(json['tmt'] as Map<String, dynamic>),
      ang: Aed.fromJson(json['ang'] as Map<String, dynamic>),
      zmw: Aed.fromJson(json['zmw'] as Map<String, dynamic>),
      hnl: Aed.fromJson(json['hnl'] as Map<String, dynamic>),
      mad: Aed.fromJson(json['mad'] as Map<String, dynamic>),
      npr: Aed.fromJson(json['npr'] as Map<String, dynamic>),
      xcd: Aed.fromJson(json['xcd'] as Map<String, dynamic>),
      omr: Aed.fromJson(json['omr'] as Map<String, dynamic>),
      hkd: Aed.fromJson(json['hkd'] as Map<String, dynamic>),
      pyg: Aed.fromJson(json['pyg'] as Map<String, dynamic>),
      mdl: Aed.fromJson(json['mdl'] as Map<String, dynamic>),
      kgs: Aed.fromJson(json['kgs'] as Map<String, dynamic>),
      mur: Aed.fromJson(json['mur'] as Map<String, dynamic>),
      btn: Aed.fromJson(json['btn'] as Map<String, dynamic>),
      inr: Aed.fromJson(json['inr'] as Map<String, dynamic>),
      yer: Aed.fromJson(json['yer'] as Map<String, dynamic>),
      imp: Aed.fromJson(json['imp'] as Map<String, dynamic>),
      dop: Aed.fromJson(json['dop'] as Map<String, dynamic>),
      ggp: Aed.fromJson(json['ggp'] as Map<String, dynamic>),
      lrd: Aed.fromJson(json['lrd'] as Map<String, dynamic>),
      zwl: Aed.fromJson(json['zwl'] as Map<String, dynamic>),
      ugx: Aed.fromJson(json['ugx'] as Map<String, dynamic>),
      vuv: Aed.fromJson(json['vuv'] as Map<String, dynamic>),
      ils: Aed.fromJson(json['ils'] as Map<String, dynamic>),
      jod: Aed.fromJson(json['jod'] as Map<String, dynamic>),
      pkr: Aed.fromJson(json['pkr'] as Map<String, dynamic>),
      bnd: Aed.fromJson(json['bnd'] as Map<String, dynamic>),
      aed: Aed.fromJson(json['aed'] as Map<String, dynamic>),
      gel: Aed.fromJson(json['gel'] as Map<String, dynamic>),
      scr: Aed.fromJson(json['scr'] as Map<String, dynamic>),
      fkp: Aed.fromJson(json['fkp'] as Map<String, dynamic>),
      gip: Aed.fromJson(json['gip'] as Map<String, dynamic>),
      sbd: Aed.fromJson(json['sbd'] as Map<String, dynamic>),
      uzs: Aed.fromJson(json['uzs'] as Map<String, dynamic>),
      mnt: Aed.fromJson(json['mnt'] as Map<String, dynamic>),
      gyd: Aed.fromJson(json['gyd'] as Map<String, dynamic>),
      bam: Bam.fromJson(json['bam'] as Map<String, dynamic>),
      top: Aed.fromJson(json['top'] as Map<String, dynamic>),
      rwf: Aed.fromJson(json['rwf'] as Map<String, dynamic>),
      bgn: Aed.fromJson(json['bgn'] as Map<String, dynamic>),
      ngn: Aed.fromJson(json['ngn'] as Map<String, dynamic>),
      shp: Aed.fromJson(json['shp'] as Map<String, dynamic>),
      fok: Aed.fromJson(json['fok'] as Map<String, dynamic>),
      lsl: Aed.fromJson(json['lsl'] as Map<String, dynamic>),
      zar: Aed.fromJson(json['zar'] as Map<String, dynamic>),
      cve: Aed.fromJson(json['cve'] as Map<String, dynamic>),
      kpw: Aed.fromJson(json['kpw'] as Map<String, dynamic>),
      cuc: Aed.fromJson(json['cuc'] as Map<String, dynamic>),
      cup: Aed.fromJson(json['cup'] as Map<String, dynamic>),
      srd: Aed.fromJson(json['srd'] as Map<String, dynamic>),
      nzd: Aed.fromJson(json['nzd'] as Map<String, dynamic>),
      mxn: Aed.fromJson(json['mxn'] as Map<String, dynamic>),
      php: Aed.fromJson(json['php'] as Map<String, dynamic>),
      sek: Aed.fromJson(json['sek'] as Map<String, dynamic>),
      jmd: Aed.fromJson(json['jmd'] as Map<String, dynamic>),
      ves: Aed.fromJson(json['ves'] as Map<String, dynamic>),
      jep: Aed.fromJson(json['jep'] as Map<String, dynamic>),
      afn: Aed.fromJson(json['afn'] as Map<String, dynamic>),
      mop: Aed.fromJson(json['mop'] as Map<String, dynamic>),
      syp: Aed.fromJson(json['syp'] as Map<String, dynamic>),
      stn: Aed.fromJson(json['stn'] as Map<String, dynamic>),
      chf: Aed.fromJson(json['chf'] as Map<String, dynamic>),
      szl: Aed.fromJson(json['szl'] as Map<String, dynamic>),
      myr: Aed.fromJson(json['myr'] as Map<String, dynamic>),
      pln: Aed.fromJson(json['pln'] as Map<String, dynamic>),
      ssp: Aed.fromJson(json['ssp'] as Map<String, dynamic>),
      khr: Aed.fromJson(json['khr'] as Map<String, dynamic>),
      lkr: Aed.fromJson(json['lkr'] as Map<String, dynamic>),
      ghs: Aed.fromJson(json['ghs'] as Map<String, dynamic>),
      ern: Aed.fromJson(json['ern'] as Map<String, dynamic>),
      bzd: Aed.fromJson(json['bzd'] as Map<String, dynamic>),
      ttd: Aed.fromJson(json['ttd'] as Map<String, dynamic>),
      ckd: Aed.fromJson(json['ckd'] as Map<String, dynamic>),
      mzn: Aed.fromJson(json['mzn'] as Map<String, dynamic>),
      irr: Aed.fromJson(json['irr'] as Map<String, dynamic>),
      cdf: Aed.fromJson(json['cdf'] as Map<String, dynamic>),
      mvr: Aed.fromJson(json['mvr'] as Map<String, dynamic>),
      mru: Aed.fromJson(json['mru'] as Map<String, dynamic>),
      czk: Aed.fromJson(json['czk'] as Map<String, dynamic>),
      byn: Aed.fromJson(json['byn'] as Map<String, dynamic>),
      all: Aed.fromJson(json['all'] as Map<String, dynamic>),
      mwk: Aed.fromJson(json['mwk'] as Map<String, dynamic>),
      sos: Aed.fromJson(json['sos'] as Map<String, dynamic>),
      rsd: Aed.fromJson(json['rsd'] as Map<String, dynamic>),
      isk: Aed.fromJson(json['isk'] as Map<String, dynamic>),
      wst: Aed.fromJson(json['wst'] as Map<String, dynamic>),
      mmk: Aed.fromJson(json['mmk'] as Map<String, dynamic>),
      thb: Aed.fromJson(json['thb'] as Map<String, dynamic>),
      lbp: Aed.fromJson(json['lbp'] as Map<String, dynamic>),
      kzt: Aed.fromJson(json['kzt'] as Map<String, dynamic>),
      tvd: Aed.fromJson(json['tvd'] as Map<String, dynamic>),
      huf: Aed.fromJson(json['huf'] as Map<String, dynamic>),
      nok: Aed.fromJson(json['nok'] as Map<String, dynamic>),
      kmf: Aed.fromJson(json['kmf'] as Map<String, dynamic>),
      sdg: Aed.fromJson(json['sdg'] as Map<String, dynamic>),
      amd: Aed.fromJson(json['amd'] as Map<String, dynamic>),
      uyu: Aed.fromJson(json['uyu'] as Map<String, dynamic>),
      sar: Aed.fromJson(json['sar'] as Map<String, dynamic>),
      bif: Aed.fromJson(json['bif'] as Map<String, dynamic>),
      uah: Aed.fromJson(json['uah'] as Map<String, dynamic>),
      sll: Aed.fromJson(json['sll'] as Map<String, dynamic>),
      bmd: Aed.fromJson(json['bmd'] as Map<String, dynamic>),
      nad: Aed.fromJson(json['nad'] as Map<String, dynamic>),
      htg: Aed.fromJson(json['htg'] as Map<String, dynamic>),
      lyd: Aed.fromJson(json['lyd'] as Map<String, dynamic>),
      pgk: Aed.fromJson(json['pgk'] as Map<String, dynamic>),
      aoa: Aed.fromJson(json['aoa'] as Map<String, dynamic>),
      idr: Aed.fromJson(json['idr'] as Map<String, dynamic>),
      ars: Aed.fromJson(json['ars'] as Map<String, dynamic>),
      pab: Aed.fromJson(json['pab'] as Map<String, dynamic>),
      jpy: Aed.fromJson(json['jpy'] as Map<String, dynamic>),
      nio: Aed.fromJson(json['nio'] as Map<String, dynamic>),
      tzs: Aed.fromJson(json['tzs'] as Map<String, dynamic>),
      tjs: Aed.fromJson(json['tjs'] as Map<String, dynamic>),
      gtq: Aed.fromJson(json['gtq'] as Map<String, dynamic>),
      bhd: Aed.fromJson(json['bhd'] as Map<String, dynamic>),
      mga: Aed.fromJson(json['mga'] as Map<String, dynamic>),
      djf: Aed.fromJson(json['djf'] as Map<String, dynamic>),
      gmd: Aed.fromJson(json['gmd'] as Map<String, dynamic>),
      bwp: Aed.fromJson(json['bwp'] as Map<String, dynamic>),
      currenciesTry:
          Aed.fromJson(json['currenciesTry'] as Map<String, dynamic>),
      azn: Aed.fromJson(json['azn'] as Map<String, dynamic>),
      crc: Aed.fromJson(json['crc'] as Map<String, dynamic>),
      vnd: Aed.fromJson(json['vnd'] as Map<String, dynamic>),
      hrk: Aed.fromJson(json['hrk'] as Map<String, dynamic>),
      qar: Aed.fromJson(json['qar'] as Map<String, dynamic>),
      cop: Aed.fromJson(json['cop'] as Map<String, dynamic>),
    );

// ignore: non_constant_identifier_names
Map<String, dynamic> _$$_CurrenciesToJson(_$_Currencies instance) =>
    <String, dynamic>{
      'bbd': instance.bbd.toJson(),
      'usd': instance.usd.toJson(),
      'xaf': instance.xaf.toJson(),
      'brl': instance.brl.toJson(),
      'eur': instance.eur.toJson(),
      'aud': instance.aud.toJson(),
      'kid': instance.kid.toJson(),
      'ron': instance.ron.toJson(),
      'lak': instance.lak.toJson(),
      'xof': instance.xof.toJson(),
      'iqd': instance.iqd.toJson(),
      'kes': instance.kes.toJson(),
      'kyd': instance.kyd.toJson(),
      'gnf': instance.gnf.toJson(),
      'tnd': instance.tnd.toJson(),
      'bob': instance.bob.toJson(),
      'cny': instance.cny.toJson(),
      'krw': instance.krw.toJson(),
      'kwd': instance.kwd.toJson(),
      'dzd': instance.dzd.toJson(),
      'awg': instance.awg.toJson(),
      'rub': instance.rub.toJson(),
      'dkk': instance.dkk.toJson(),
      'gbp': instance.gbp.toJson(),
      'twd': instance.twd.toJson(),
      'cad': instance.cad.toJson(),
      'fjd': instance.fjd.toJson(),
      'xpf': instance.xpf.toJson(),
      'pen': instance.pen.toJson(),
      'clp': instance.clp.toJson(),
      'egp': instance.egp.toJson(),
      'mkd': instance.mkd.toJson(),
      'bdt': instance.bdt.toJson(),
      'sgd': instance.sgd.toJson(),
      'etb': instance.etb.toJson(),
      'bsd': instance.bsd.toJson(),
      'tmt': instance.tmt.toJson(),
      'ang': instance.ang.toJson(),
      'zmw': instance.zmw.toJson(),
      'hnl': instance.hnl.toJson(),
      'mad': instance.mad.toJson(),
      'npr': instance.npr.toJson(),
      'xcd': instance.xcd.toJson(),
      'omr': instance.omr.toJson(),
      'hkd': instance.hkd.toJson(),
      'pyg': instance.pyg.toJson(),
      'mdl': instance.mdl.toJson(),
      'kgs': instance.kgs.toJson(),
      'mur': instance.mur.toJson(),
      'btn': instance.btn.toJson(),
      'inr': instance.inr.toJson(),
      'yer': instance.yer.toJson(),
      'imp': instance.imp.toJson(),
      'dop': instance.dop.toJson(),
      'ggp': instance.ggp.toJson(),
      'lrd': instance.lrd.toJson(),
      'zwl': instance.zwl.toJson(),
      'ugx': instance.ugx.toJson(),
      'vuv': instance.vuv.toJson(),
      'ils': instance.ils.toJson(),
      'jod': instance.jod.toJson(),
      'pkr': instance.pkr.toJson(),
      'bnd': instance.bnd.toJson(),
      'aed': instance.aed.toJson(),
      'gel': instance.gel.toJson(),
      'scr': instance.scr.toJson(),
      'fkp': instance.fkp.toJson(),
      'gip': instance.gip.toJson(),
      'sbd': instance.sbd.toJson(),
      'uzs': instance.uzs.toJson(),
      'mnt': instance.mnt.toJson(),
      'gyd': instance.gyd.toJson(),
      'bam': instance.bam.toJson(),
      'top': instance.top.toJson(),
      'rwf': instance.rwf.toJson(),
      'bgn': instance.bgn.toJson(),
      'ngn': instance.ngn.toJson(),
      'shp': instance.shp.toJson(),
      'fok': instance.fok.toJson(),
      'lsl': instance.lsl.toJson(),
      'zar': instance.zar.toJson(),
      'cve': instance.cve.toJson(),
      'kpw': instance.kpw.toJson(),
      'cuc': instance.cuc.toJson(),
      'cup': instance.cup.toJson(),
      'srd': instance.srd.toJson(),
      'nzd': instance.nzd.toJson(),
      'mxn': instance.mxn.toJson(),
      'php': instance.php.toJson(),
      'sek': instance.sek.toJson(),
      'jmd': instance.jmd.toJson(),
      'ves': instance.ves.toJson(),
      'jep': instance.jep.toJson(),
      'afn': instance.afn.toJson(),
      'mop': instance.mop.toJson(),
      'syp': instance.syp.toJson(),
      'stn': instance.stn.toJson(),
      'chf': instance.chf.toJson(),
      'szl': instance.szl.toJson(),
      'myr': instance.myr.toJson(),
      'pln': instance.pln.toJson(),
      'ssp': instance.ssp.toJson(),
      'khr': instance.khr.toJson(),
      'lkr': instance.lkr.toJson(),
      'ghs': instance.ghs.toJson(),
      'ern': instance.ern.toJson(),
      'bzd': instance.bzd.toJson(),
      'ttd': instance.ttd.toJson(),
      'ckd': instance.ckd.toJson(),
      'mzn': instance.mzn.toJson(),
      'irr': instance.irr.toJson(),
      'cdf': instance.cdf.toJson(),
      'mvr': instance.mvr.toJson(),
      'mru': instance.mru.toJson(),
      'czk': instance.czk.toJson(),
      'byn': instance.byn.toJson(),
      'all': instance.all.toJson(),
      'mwk': instance.mwk.toJson(),
      'sos': instance.sos.toJson(),
      'rsd': instance.rsd.toJson(),
      'isk': instance.isk.toJson(),
      'wst': instance.wst.toJson(),
      'mmk': instance.mmk.toJson(),
      'thb': instance.thb.toJson(),
      'lbp': instance.lbp.toJson(),
      'kzt': instance.kzt.toJson(),
      'tvd': instance.tvd.toJson(),
      'huf': instance.huf.toJson(),
      'nok': instance.nok.toJson(),
      'kmf': instance.kmf.toJson(),
      'sdg': instance.sdg.toJson(),
      'amd': instance.amd.toJson(),
      'uyu': instance.uyu.toJson(),
      'sar': instance.sar.toJson(),
      'bif': instance.bif.toJson(),
      'uah': instance.uah.toJson(),
      'sll': instance.sll.toJson(),
      'bmd': instance.bmd.toJson(),
      'nad': instance.nad.toJson(),
      'htg': instance.htg.toJson(),
      'lyd': instance.lyd.toJson(),
      'pgk': instance.pgk.toJson(),
      'aoa': instance.aoa.toJson(),
      'idr': instance.idr.toJson(),
      'ars': instance.ars.toJson(),
      'pab': instance.pab.toJson(),
      'jpy': instance.jpy.toJson(),
      'nio': instance.nio.toJson(),
      'tzs': instance.tzs.toJson(),
      'tjs': instance.tjs.toJson(),
      'gtq': instance.gtq.toJson(),
      'bhd': instance.bhd.toJson(),
      'mga': instance.mga.toJson(),
      'djf': instance.djf.toJson(),
      'gmd': instance.gmd.toJson(),
      'bwp': instance.bwp.toJson(),
      'currenciesTry': instance.currenciesTry.toJson(),
      'azn': instance.azn.toJson(),
      'crc': instance.crc.toJson(),
      'vnd': instance.vnd.toJson(),
      'hrk': instance.hrk.toJson(),
      'qar': instance.qar.toJson(),
      'cop': instance.cop.toJson(),
    };
